name: montanhas_server
description: A web-server
version: 1.0.0

environment:
  sdk: '>=2.16.0 <3.0.0'


dependencies:
  shelf_router: ^1.1.2
  firebase_dart: ^1.0.5
  uuid: ^3.0.5
  jaguar_jwt: ^3.0.0
  args:
  validators: ^3.0.0

dev_dependencies:
  lints: ^1.0.0
